name: CI
permissions:
  contents: read

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    name: Continuous integration pipeline
    runs-on: ubuntu-24.04
    timeout-minutes: 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
            version: "0.6.8"
            enable-cache: true
            cache-dependency-glob: "uv.lock"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Lint code base
        run: uv run ruff check

      - name: Run type checking
        run: uv run pyright

      - name: Run tests
        run: uv run pytest tests
